SampleWebApplication/Models/ErrorViewModel.cs
using System;

namespace SampleWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SampleWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SampleWebApplication.Models;

namespace SampleWebApplication.Controllers
{
    /// <summary>
    /// Author: Bilal Khattak
    /// </summary>
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SampleWebApplication/Controllers/RegularExpressionValidatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SampleWebApplication.Controllers
{
    /// <summary>
    /// Author: Bilal Khattak
    /// </summary>
    public class RegularExpressionValidatorController : Controller
    {
        // GET: RegularExpressionValidatorController
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(IFormCollection collection)
        {
            var pattern = collection["regularExpression"];
            var text = collection["regularExpressionText"];


            // Create a Regex  
            var rg = new Regex(@"{\b[" + pattern + @"]\w+}");

            // Get all matches  
            var matchedWords = rg.Matches(text);

            var listMatchedWords = new List<string>();
            for (int count = 0; count < matchedWords.Count; count++)
            {
                listMatchedWords.Add(matchedWords[count].Value);
            }

            ViewBag.RegularExpression = pattern;
            ViewBag.RegularExpressionText = text;

            ViewBag.RegularExpressionresult = listMatchedWords;

            return View();
        }

    }
}

SampleWebApplication/Controllers/TextAnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SampleWebApplication.Controllers
{
    public class TextAnalysisController : Controller
    {
        // GET: TextAnalysisController
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(IFormCollection collection)
        {
            var text = collection["textToAnalyze"];
            var word = collection["word"];

            var count = BusinessLogic.StringHelper.GetWordOccurancesInASentence(text, word);

            ViewBag.text = text;
            ViewBag.word = word;
            ViewBag.count = count;

            return View();
        }

    }
}

SampleWebApplication/Controllers/VocabularyBuilderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SampleWebApplication.Controllers
{
    /// <summary>
    /// Author: Muhammad shoaib
    /// </summary>
    
    public class VocabularyBuilderController : Controller
    {
        // GET: VocabularyBuilderController
        public ActionResult Index()
        {
            return View();
        }

    }
}

SampleWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <p>
        This appllication would help students learn to perform some text analysis. Also it would help them to learn and write regular expression.
        Furthermore, it would help them to build some vaocabulary.
    </p>
</div>

SampleWebApplication/Views/RegularExpressionValidator/Index.cshtml
@{
    ViewData["Title"] = "Regulare Expression validator";
    var listMatchedWords = new List<string>();

    listMatchedWords = (ViewBag.RegularExpressionresult as List<string>);
    if(listMatchedWords == null)
    {
        listMatchedWords = new List<string>();
    }
}

<form action="/RegularExpressionValidator/Index" method="post">
    <div class="text-center">
        <p>
            <table>
                <tr>
                    <td>Regular expression:</td>
                    <td><input type="text" id="regularExpression" name="regularExpression" value="@ViewBag.RegularExpression" /></td>
                </tr>
                <tr>
                    <td>Text:</td>
                    <td><input type="text" id="regularExpressionText" name="regularExpressionText" value="@ViewBag.RegularExpressionText" /></td>
                </tr>
                <tr>
                    <td>Result:</td>
                    <td>
                        <textarea id="regularExpressionresult" name="regularExpressionresult" readonly="readonly" rows="4" style="width: 90%;">
                            @foreach (var word in listMatchedWords)
                            {
                                @(word + Environment.NewLine)
                            }
                        </textarea>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Validate Regular Expression" /></td>
                </tr>
            </table>
        </p>
    </div>
</form>

SampleWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Test application for educational purposes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TextAnalysis" asp-action="Index">Text analysis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegularExpressionValidator" asp-action="Index">Regular Expression Validator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VocabularyBuilder" asp-action="Index">Vocabulary builder</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Test application for educational purposes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SampleWebApplication/Views/TextAnalysis/Index.cshtml
@{
    ViewData["Title"] = "Text analysis";
}


<form action="/TextAnalysis/Index" method="post">
    <div class="text-center">
        <p>
            <table>
                <tr>
                    <td>Text:</td>
                    <td>
                        <textarea id="textToAnalyze" name="textToAnalyze" rows="4" style="width: 90%;">@ViewBag.text</textarea>
                    </td>
                </tr>
                <tr>
                    <td>Word:</td>
                    <td><input type="text" id="word" name="word" value="@ViewBag.word" /></td>
                </tr>
                <tr>
                    <td>Total count:</td>
                    <td>@ViewBag.count</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Count words" /></td>
                </tr>
            </table>
        </p>
    </div>
</form>

SampleWebApplication/Views/VocabularyBuilder/Index.cshtml
@{
    ViewData["Title"] = "Vocabulary builder";
}

<div class="text-center">
    <p>
        User interface for building vocabulary ....
    </p>
</div>